from __future__ import annotations

import os
# Suppress NeMo log levels before framework initialization
os.environ['NEMO_LOG_LEVEL'] = 'ERROR'

import logging
import queue
import tempfile
import time
import warnings
from collections.abc import Generator
from dataclasses import dataclass
from pathlib import Path

# Silence all standard Python warnings
warnings.filterwarnings('ignore')

import nemo.collections.asr as nemo_asr
import numpy as np
import sounddevice as sd
import soundfile as sf
import torch
from nemo.utils import logging as nemo_logging
from silero_vad import load_silero_vad


# ============================================================
# LOGGING SUPPRESSION
# ============================================================

class DropNeMoWarnings(logging.Filter):
    """Filter out non-error logs generated by NeMo."""

    def filter(self, record: logging.LogRecord) -> bool:
        return record.levelno >= logging.ERROR


def silence_nemo_loggers() -> None:
    """Completely suppress NeMo warning and info outputs."""
    nemo_logger = logging.getLogger('nemo_logger')
    nemo_logger.setLevel(logging.ERROR)
    nemo_filter = DropNeMoWarnings()

    nemo_logger.addFilter(nemo_filter)
    for handler in nemo_logger.handlers:
        handler.addFilter(nemo_filter)
        handler.setLevel(logging.ERROR)

    # Disable warning callable to prevent transcribe() from resetting level
    nemo_logging.warning = lambda *args, **kwargs: None


silence_nemo_loggers()


# ============================================================
# CONFIGURATION
# ============================================================

@dataclass(frozen=True)
class ASRConfig:
    """Configuration parameters for ASR and Voice Activity Detection."""

    model_path: Path = Path('./shenava-koochik/shenava-koochik-1.0.nemo')
    sample_rate: int = 16_000
    channels: int = 1
    vad_chunk_size: int = 512
    end_silence_ms: int = 800
    min_speech_ms: int = 400
    vad_threshold: float = 0.65
    min_rms_energy: float = 0.015

    # Device selection: False for CPU, True for GPU
    use_cuda: bool = False
    cuda_device_id: int = 0

    @property
    def resolved_device(self) -> str:
        """Resolve valid PyTorch execution device."""
        if self.use_cuda and torch.cuda.is_available():
            return f'cuda:{self.cuda_device_id}'
        return 'cpu'


# ============================================================
# ASR INFERENCE ENGINE
# ============================================================

class ShenavaASR:
    """Real-time Voice Activity Detection and Speech Recognition pipeline."""

    def __init__(self, config: ASRConfig = ASRConfig()) -> None:
        self.config = config
        self._verify_model()

        self.asr_model = self._load_asr_model()
        self.vad_model = self._load_vad_model()

        # Re-apply logger silencing after model restoration
        silence_nemo_loggers()

        self._audio_queue: queue.Queue[np.ndarray] = queue.Queue()

    def _verify_model(self) -> None:
        """Ensure NeMo model weights exist on disk."""
        if not self.config.model_path.exists():
            raise FileNotFoundError(
                f'ASR model checkpoint not found: {self.config.model_path}'
            )

    def _load_asr_model(self) -> nemo_asr.models.ASRModel:
        """Load and configure the NeMo ASR model."""
        model = nemo_asr.models.ASRModel.restore_from(
            restore_path=str(self.config.model_path),
            map_location=self.config.resolved_device,
        )
        model.eval()

        if hasattr(model, 'change_decoding_strategy'):
            try:
                model.change_decoding_strategy(
                    decoder_type='ctc',
                    decoding_cfg={'strategy': 'greedy_batch'},
                )
            except Exception as exc:
                print(f'Warning: Could not set decoding strategy: {exc}')

        return model

    def _load_vad_model(self) -> torch.nn.Module:
        """Initialize the Silero VAD neural network."""
        vad = load_silero_vad()
        vad.eval()
        return vad

    def _is_loud_enough(self, audio: np.ndarray) -> bool:
        """Check if audio RMS energy surpasses the noise floor threshold."""
        rms = float(np.sqrt(np.mean(audio**2)))
        return rms >= self.config.min_rms_energy

    def transcribe(self, audio: np.ndarray) -> str:
        """Normalize audio amplitude and transcribe via NeMo ASR."""
        if not self._is_loud_enough(audio):
            return ''

        peak = float(np.max(np.abs(audio)))
        if peak > 0:
            audio = (audio / peak) * 0.95

        with tempfile.NamedTemporaryFile(suffix='.wav', delete=True) as temp_wav:
            sf.write(temp_wav.name, audio, self.config.sample_rate)

            with torch.inference_mode():
                results = self.asr_model.transcribe(
                    [temp_wav.name],
                    batch_size=1,
                    verbose=False,
                )

        if not results:
            return ''

        prediction = results[0]
        if hasattr(prediction, 'text'):
            prediction = prediction.text

        return str(prediction).strip()

    def _audio_callback(
        self,
        indata: np.ndarray,
        frames: int,
        time_info: object,
        status: sd.CallbackFlags,
    ) -> None:
        """Stream input audio frames directly into the processing queue."""
        if status:
            print(f'Audio stream status: {status}')
        self._audio_queue.put(indata[:, 0].copy())

    def _open_microphone(self) -> sd.InputStream:
        """Use the same audio format for continuous and single-turn listening."""
        return sd.InputStream(
            samplerate=self.config.sample_rate,
            channels=self.config.channels,
            dtype='float32',
            blocksize=self.config.vad_chunk_size,
            callback=self._audio_callback,
        )

    def _has_speech(self, chunk: np.ndarray) -> bool:
        """Check one audio chunk with Silero VAD."""
        with torch.no_grad():
            probability = self.vad_model(
                torch.from_numpy(chunk), self.config.sample_rate,
            ).item()
        return probability > self.config.vad_threshold

    def listen(self) -> Generator[str, None, None]:
        """Stream microphone input and yield transcribed sentences upon speech completion."""
        end_silence_samples = int(
            self.config.sample_rate * (self.config.end_silence_ms / 1000)
        )
        min_speech_samples = int(
            self.config.sample_rate * (self.config.min_speech_ms / 1000)
        )

        speech_buffer: list[np.ndarray] = []
        is_speaking = False
        silence_samples = 0

        self.vad_model.reset_states()

        with self._open_microphone():
            while True:
                chunk = self._audio_queue.get()
                if self._has_speech(chunk):
                    if not is_speaking:
                        is_speaking = True
                    speech_buffer.append(chunk)
                    silence_samples = 0
                elif is_speaking:
                    speech_buffer.append(chunk)
                    silence_samples += len(chunk)

                    if silence_samples >= end_silence_samples:
                        captured_audio = np.concatenate(speech_buffer)
                        speech_buffer.clear()
                        is_speaking = False
                        silence_samples = 0

                        self.vad_model.reset_states()

                        if len(captured_audio) >= min_speech_samples:
                            text = self.transcribe(captured_audio)
                            if text:
                                yield text

    def listen_utterance(self, timeout: float | None = None, phrase_time_limit: float | None = 20.0) -> str:
        """Capture a single speech utterance and close the microphone stream immediately."""
        end_silence_samples = int(self.config.sample_rate * (self.config.end_silence_ms / 1000))
        min_speech_samples = int(self.config.sample_rate * (self.config.min_speech_ms / 1000))

        while not self._audio_queue.empty():
            try:
                self._audio_queue.get_nowait()
            except queue.Empty:
                break

        speech_buffer: list[np.ndarray] = []
        is_speaking = False
        silence_samples = 0
        start_time = time.monotonic()
        speech_start_time: float | None = None

        self.vad_model.reset_states()

        with self._open_microphone():
            while True:
                if not is_speaking and timeout is not None:
                    if (time.monotonic() - start_time) > timeout:
                        break

                if is_speaking and phrase_time_limit is not None and speech_start_time is not None:
                    if (time.monotonic() - speech_start_time) > phrase_time_limit:
                        break

                try:
                    chunk = self._audio_queue.get(timeout=0.1)
                except queue.Empty:
                    continue

                if self._has_speech(chunk):
                    if not is_speaking:
                        is_speaking = True
                        speech_start_time = time.monotonic()
                    speech_buffer.append(chunk)
                    silence_samples = 0
                elif is_speaking:
                    speech_buffer.append(chunk)
                    silence_samples += len(chunk)
                    if silence_samples >= end_silence_samples:
                        break

        if speech_buffer:
            captured_audio = np.concatenate(speech_buffer)
            if len(captured_audio) >= min_speech_samples:
                return self.transcribe(captured_audio)

        return ''


# ============================================================
# ENTRY POINT
# ============================================================

def main() -> None:
    config = ASRConfig(use_cuda=False)
    asr = ShenavaASR(config)

    print(f'ASR ready on device: {config.resolved_device}')
    print('Listening... Speak into the microphone (Ctrl+C to stop).\n')

    try:
        for recognized_text in asr.listen():
            print(f'Recognized: {recognized_text}')
    except KeyboardInterrupt:
        print('\nAudio capture terminated.')


if __name__ == '__main__':
    main()
